### ISSUE TITLE
Installation exceptions

### ISSUE THREAD

**Issue by sevenb23** [RIPE-NCC/whois#270]
I was trying to install the RIPE software, following the instructions from https://github.com/RIPE-NCC/whois/wiki/Installation-instructions. However, When I try to start the whois server, I get this:

Starting whois...
Waiting for the server to come up... (If you know what you are doing, hit ESC to skip waiting)
Status: 	at java.lang.Thread.run(Thread.java:745)
Server does not seem to be up after 480 seconds, giving up. Here is the end of var/console.log:
-------------------------------------------------------------------------------------
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2014-09-16 11:34:33,332 ERROR [IpTreeUpdater] Unexpected
java.lang.IllegalArgumentException: No cached ipTree for source: RIPE
	at net.ripe.db.whois.common.iptree.IpTreeCacheManager.update(IpTreeCacheManager.java:181)
	at net.ripe.db.whois.common.iptree.IpTreeUpdater$3.execute(IpTreeUpdater.java:114)
	at net.ripe.db.whois.common.iptree.IpTreeUpdater$4.run(IpTreeUpdater.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
-------------------------------------------------------------------------------------

Please let me know if I'm missing something.

**Comment by timbru** [comment]
can't reproduce
