### ISSUE TITLE
Installation whois-client failure

### ISSUE THREAD

**Issue by c1982** [RIPE-NCC/whois#405]
Hi,
I try install whois server on my ubuntu (wily) server. But I could not install.

I execute command line:

`sudo mvn clean install -Prelease -X`

and throw exception on whois-client step.

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default) on project whois-client: Command execution failed. Process exited with an error: 127 (Exit value: 127) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default) on project whois-client: Command execution failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
        ... 22 more
```

also, I catch a warning in debug logs.

```
[DEBUG] Executing command line: src/main/parser/bin/generateByaccs
testing if src/main/parser/bin/yacc.linux binary is executable...
WARNING: suitable yacc binary not found - will compile the byaccj-p2 tool
~/whois-whois-1.87.3/whois-client/src/main/parser/byaccj-p2/src ~/whois-whois-1.87.3/whois-client
src/main/parser/bin/generateByaccs: line 32: make: command not found
```

How can i fix this?

Thanks.

**Comment by c1982** [comment]
Another tip for debug.

I try execute manually from warning msg command about byaccj-p2.

`sudo ./whois-whois-1.87.3/whois-client/src/main/parser/bin/generateByaccs`

return this error.

`./generateByaccs: line 31: pushd: src/main/parser/byaccj-p2/src: No such file or directory`

**Comment by functure** [comment]
For anyone who encounters the same issue again, it is probably because /usr/bin/yacc.linux is compiled for 32-bit and you are trying to execute a 32-bit binary on your 64-bit machine.

If you have a 64-bit machine you can install libc6-i386 for multiarch support and try mvn install again.
