### ISSUE TITLE
Error When Creating, Updating, and Deleting Object from REST API

### ISSUE THREAD

**Issue by DavidPratama** [RIPE-NCC/whois#431]
I'm importing data from APNIC RPSL DB, and it's successfully imported. I'm on progress building IDNIC whois server.

 But when I'm trying to perform post, update, and delete request from rest api, I got an error "Unexpected error"
I'm sure that i have right maintainer password. Is this problem with my database or anyone facing the same problem?

```
2017-05-09 02:08:38,816 ERROR [UpdateRequestHandler] Updating [person] DA212-AP   David Pratama

org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:477)
	at org.springframework.jdbc.core.JdbcTemplate.queryForInt(JdbcTemplate.java:488)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao.setUpdateLock_aroundBody0(JdbcUpdateLockDao.java:30)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao$AjcClosure1.run(JdbcUpdateLockDao.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao.setUpdateLock(JdbcUpdateLockDao.java:24)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler.handle_aroundBody0(SingleUpdateHandler.java:88)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler$AjcClosure1.run(SingleUpdateHandler.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler.handle(SingleUpdateHandler.java:87)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.attemptUpdates(UpdateRequestHandler.java:158)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.processUpdateQueue(UpdateRequestHandler.java:133)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.handleUpdates(UpdateRequestHandler.java:103)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.handleUpdateRequest(UpdateRequestHandler.java:90)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.handle(UpdateRequestHandler.java:64)
	at net.ripe.db.whois.api.rest.InternalUpdatePerformer.performUpdate(InternalUpdatePerformer.java:90)
	at net.ripe.db.whois.api.rest.WhoisRestService.create(WhoisRestService.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at net.ripe.db.whois.api.rest.MaintenanceModeFilter.doFilter(MaintenanceModeFilter.java:45)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at net.ripe.db.whois.api.httpserver.ExtensionOverridesAcceptHeaderFilter.doFilter(ExtensionOverridesAcceptHeaderFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at net.ripe.db.whois.api.httpserver.RemoteAddressFilter.doFilter(RemoteAddressFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)


```
Here the data I sent with post request

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<whois-resources>
    <objects>
        <object type="person">
            <source id="apnic"/>
            <attributes>
                <attribute name="person" value="David Pratama"/>
                <attribute name="address" value="Duren Tiga"/>
                <attribute name="phone" value="+62-85729677738"/>
                <attribute name="e-mail" value="david@arsen.co.id"/>
                <attribute name="mnt-by" value="MAINT-ID-ARSEN"/>
                <attribute name="nic-hdl" value="DA212-AP"/>
                <attribute name="source" value="apnic"/>
            </attributes>
        </object>
    </objects>
</whois-resources>
```

And this is the error reponse I got

```
<?xml version="1.0" encoding="UTF-8"?>
<whois-resources xmlns:xlink="http://www.w3.org/1999/xlink">
    <link xlink:type="locator" xlink:href="http://203.119.13.106:1080/apnic/person"/>
    <errormessages>
        <errormessage severity="Error" text="Unexpected error occurred"/>
    </errormessages>
    <terms-and-conditions xlink:type="locator" xlink:href="http://www.ripe.net/db/support/db-terms-conditions.pdf"/>
</whois-resources>
```

# Update

After I tried debug the mysql query, I found this query when running update, create, and delete request

```
2017-05-09T03:59:22.720730Z	  295 Query	SELECT @@session.tx_isolation
2017-05-09T03:59:22.721259Z	  295 Query	SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED
2017-05-09T03:59:22.721512Z	  295 Query	SET autocommit=0
2017-05-09T03:59:22.721982Z	  295 Query	select @@tx_isolation
2017-05-09T03:59:22.722752Z	  295 Query	SELECT global_lock FROM update_lock WHERE global_lock = 0 FOR UPDATE
2017-05-09T03:59:22.723435Z	  295 Query	rollback
2017-05-09T03:59:22.723783Z	  295 Query	SET autocommit=1
2017-05-09T03:59:22.724107Z	  295 Query	SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
```

Then I try to insert 0 to global lock table

`INSERT INTO update_lock (global_lock) VALUE (0);`

And I can perform the request. 
But what is the purpose of update_lock table? Am I miss a step so that table is empty?

**Comment by eshryane** [comment]
Thanks for letting us know, I've updated the installation instructions page to mention the data.sql scripts also need to be executed.
`
use WHOIS_LOCAL;
source ./whois-commons/src/main/resources/whois_data.sql
use INTERNALS_LOCAL;
source ./whois-commons/src/main/resources/internals_data.sql
`
