### ISSUE TITLE
Test RIPE, Not POST method, and PUT method remove the '/whois'

### ISSUE THREAD

**Issue by cengn-tao** [RIPE-NCC/whois#514]
Just pulled the latest the code and followed the installation instructions.
Trying to POST a person object into test RIPE.  It replied with "Method not found". So I used PUT instead. From the response, I can see that the '/whois' is removed from "href". I think that may be the reason of the error it reported in the response.

http://10.189.32.68:1080/whois/test/mntner/TEST-DBM-MNT?password=emptypassword

{
  "link" : {
    "type" : "locator",
    "href" : "http://10.189.32.68:1080/test/mntner/TEST-DBM-MNT"
  },
  "errormessages" : {
    "errormessage" : [ {
      "severity" : "Error",
      "text" : "Object type and key specified in URI (%s: %s) do not match the WhoisResources contents",
      "args" : [ {
        "value" : "mntner"
      }, {
        "value" : "TEST-DBM-MNT"
      } ]
    } ]
  },
  "terms-and-conditions" : {
    "type" : "locator",
    "href" : "http://www.ripe.net/db/support/db-terms-conditions.pdf"
  }
}

**Comment by eshryane** [comment]
Hello, it's possible to use POST to create a new person object, here is an example.

Beforehand, I created a mntner AAA1111-MNT with a password "password".

`curl -v -X POST -d @input -H "Content-Type: application/json" http://localhost:1081/whois/test/person.json?password=password`

With request body in file "input"

```
{
  "objects": {
    "object": [
      {
        "attributes": {
          "attribute": [
            {
              "name": "person",
              "value": "Test Person"
            },
            {
              "name": "address",
              "value": "Amsterdam"
            },
            {
              "name": "phone",
              "value": "+3122"
            },
            {
              "name": "nic-hdl",
              "value": "AUTO-1"
            },
            {
              "name": "mnt-by",
              "value": "AAA1111-MNT"
            },
            {
              "name": "source",
              "value": "TEST"
            }
          ]
        }
      }
    ]
  }
}

```

**Comment by eshryane** [comment]
You are correct, the Whois REST API servlet uses the context path /whois/ by default, but it's stripped out from the response.

**Comment by cengn-tao** [comment]
Thanks eshryane. Could you please also show me what's the curl link and the JSON request body when you created the mntner AAA1111-MNT?

**Comment by eshryane** [comment]
It depends if you have a completely empty local database or not.

If you don't have any existing maintainers in your local database, then you will need to bootstrap the database using JMX.

* Prepare a text file containing RPSL objects, for example a maintainer and a person, which reference each other.
* Download Jmxterm from e.g. http://wiki.cyclopsgroup.org/jmxterm/
* Run Jmxterm specifying the whois server PID: java -jar jmxterm.jar <pid>
   * bean net.ripe.db.whois:name=Bootstrap
   * run loadDump "comment" "/path/to/file"

The bootstrap process is explained in https://github.com/RIPE-NCC/whois/wiki/Installation-instructions 

If you do have an existing maintainer, then you can use the example I gave earlier, by reference that existing maintainer in the mnt-by attribute, and provide its password as a query parameter.

**Comment by cengn-tao** [comment]
Thanks eshryane. I am following your instructions and using the mntner TEST-DBM-MNT to create a person object. Here is the maintainer. 
**mntner:         TEST-DBM-MNT
descr:          Mntner for TEST DBM objects.
admin-c:        AA1-TEST
tech-c:         AA2-TEST
upd-to:         bitbucket@ripe.net
mnt-nfy:        bitbucket@ripe.net
auth:           MD5-PW $1$N2zhyJ3g$hzX7XTL84DtBkCWhBZE2c/
remarks:        **********************************************************************
remarks:        Password is "emptypassword" without the quotes.
remarks:        **********************************************************************
notify:         bitbucket@ripe.net
mnt-by:         TEST-ROOT-MNT
remarks:        This is an automatically created object.
source:         TEST**

Here is the curl and request body:
curl -v -X POST -d @input -H "Content-Type: application/json" -H 'Accept: application/json'  'http://localhost:1080/whois/test/person?password=emptypassword'

{
  "objects": {
    "object": [
      {
        "attributes": {
          "attribute": [
            {
              "name": "person",
              "value": "Tao Zhang"
            },
            {
              "name": "address",
              "value": "Amsterdam"
            },
            {
              "name": "phone",
              "value": "+3122"
            },
            {
              "name": "nic-hdl",
              "value": "CANARIE-1"
            },
            {
              "name": "mnt-by",
              "value": "TEST-DBM-MNT"
            },
            {
              "name": "source",
              "value": "TEST"
            }
          ]
        }
      }
    ]
  }
}



This is the error I got. Don't know where I got it wrong.

[root@localhost tzhang]# curl -v -X POST -d @input -H "Content-Type: application/json" -H 'Accept: application/json'  'http://localhost:1080/whois/test/person?password=emptypassword'
* About to connect() to localhost port 1080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 1080 (#0)
> POST /whois/test/person?password=emptypassword HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:1080
> Content-Type: application/json
> Accept: application/json
> Content-Length: 666
>
* upload completely sent off: 666 out of 666 bytes
< HTTP/1.1 400 Bad Request
< Date: Fri, 02 Nov 2018 16:06:18 GMT
< Content-Type: application/json
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< Vary: Accept-Encoding
< Content-Length: 352
< Server: Jetty(9.4.z-SNAPSHOT)
<
{
  "link" : {
    "type" : "locator",
    "href" : "http://localhost:1080/test/person"
  },
  "errormessages" : {
    "errormessage" : [ {
      "severity" : "Error",
      "text" : "Unexpected error occurred"
    } ]
  },
  "terms-and-conditions" : {
    "type" : "locator",
    "href" : "http://www.ripe.net/db/support/db-terms-conditions.pdf"
  }
* Connection #0 to host localhost left intact

**Comment by eshryane** [comment]
Can you include the error message from Whois in var/console.log ?

**Comment by cengn-tao** [comment]
2018-11-02 12:11:27,241 ERROR [UpdateRequestHandler] Updating [person] CANARIE-1   Tao Zhang
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:69)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:499)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:504)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao.setUpdateLock_aroundBody0(JdbcUpdateLockDao.java:30)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao$AjcClosure1.run(JdbcUpdateLockDao.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao.setUpdateLock(JdbcUpdateLockDao.java:24)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler.handle_aroundBody0(SingleUpdateHandler.java:85)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler$AjcClosure1.run(SingleUpdateHandler.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at net.ripe.db.whois.update.handler.SingleUpdateHandler.handle(SingleUpdateHandler.java:84)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.attemptUpdatesOneByOne(UpdateRequestHandler.java:161)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.processUpdateQueueOneByOne(UpdateRequestHandler.java:136)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.handleUpdateRequest(UpdateRequestHandler.java:103)
	at net.ripe.db.whois.update.handler.UpdateRequestHandler.handle(UpdateRequestHandler.java:67)
	at net.ripe.db.whois.api.rest.InternalUpdatePerformer.performUpdates(InternalUpdatePerformer.java:94)
	at net.ripe.db.whois.api.rest.InternalUpdatePerformer.performUpdate(InternalUpdatePerformer.java:87)
	at net.ripe.db.whois.api.rest.WhoisRestService.create(WhoisRestService.java:237)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at net.ripe.db.whois.api.rest.MaintenanceModeFilter.doFilter(MaintenanceModeFilter.java:45)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at net.ripe.db.whois.api.httpserver.ExtensionOverridesAcceptHeaderFilter.doFilter(ExtensionOverridesAcceptHeaderFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at net.ripe.db.whois.api.httpserver.RemoteAddressFilter.doFilter(RemoteAddressFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cengn-tao** [comment]
It's the same.

2018-11-02 12:29:48,542 ERROR [UpdateRequestHandler] Updating [person] TZ1-TEST   Tao Zhang
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:69)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:499)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:504)
	at net.ripe.db.whois.common.dao.jdbc.JdbcUpdateLockDao.setUpdateLock_aroundBody0(JdbcUpdateLockDao.java:30)
....

**Comment by cengn-tao** [comment]
Hi eshryane, I was checking my installation process. 
In the documentation, it says:
**Create the databases WHOIS_LOCAL, MAILUPDATES_LOCAL, dnscheck_local, ACL_LOCAL, INTERNALS_LOCAL.**
I actually didn't create the dnscheck_local database since I didn't find the schema in the **./whois-commons/src/main/resources/** folder. There is a **versions_schema.sql** in the folder. Should I create this database? If so, what the name of the debase would be? VERSIONS or VERSIONS_LOCAL?

**Comment by cengn-tao** [comment]
Hi eshryane,
My problem is exactly the same as Issue #431. I need to manually insert a number into table update_lock.   
INSERT INTO update_lock (global_lock) VALUE (0);
After I did that, I can POST data now.

**Comment by eshryane** [comment]
Thanks for letting me know! We will update the installation instructions.

**Comment by eshryane** [comment]
I've updated the installation instructions page to mention the data.sql scripts also need to be executed.
```
use WHOIS_LOCAL;
source ./whois-commons/src/main/resources/whois_data.sql
use INTERNALS_LOCAL;
source ./whois-commons/src/main/resources/internals_data.sql
```
