### ISSUE TITLE
Missing properties file and bug (Installation Instructions deprecated?)

### ISSUE THREAD

**Issue by SaltyHash123** [RIPE-NCC/whois#796]
Hey there,

i managed to run through the installations but am facing now some issues:
1) there exists no` whois.properties` file under the path `whois-commons/src/main/resources/whois.properties`
(removed at commit a4650eb2d3ea9e5dee75a8aa70602b9ba7f921ce)
What should i do now instead of setting the properties file?

2) when i run `./whois.init start`  i get the following error message (see below)
It mentions the missing properties (but only as INFO) and complains about unresolveable acl.database.url
Am i supposed to configure there something.
Note: My working environment is isolated and cannot communicate to the internet...

ERROR LOG:
`Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-04-13T14:51:19,374 INFO  [WhoisProfile] No active profile specified, using default one
2021-04-13T14:51:20,473 INFO  [ConfigurationClassParser] Properties location [file:${whois.config}] not resolvable: properties (No such file or directory)
2021-04-13T14:51:20,625 INFO  [WhoisRipePropertyResolver] Instance name is [CENSORED]
2021-04-13T14:51:20,635 WARN  [ClassPathXmlApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'aclDataSource' defined in class path resource [applicationContext-commons.xml]: Could not resolve placeholder 'acl.database.url' in value "${acl.database.url}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'acl.database.url' in value "${acl.database.url}"
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'aclDataSource' defined in class path resource [applicationContext-commons.xml]: Could not resolve placeholder 'acl.database.url' in value "${acl.database.url}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'acl.database.url' in value "${acl.database.url}"
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:228)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:182)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:157)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:325)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:183)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:745)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:563)
        at net.ripe.db.whois.common.profiles.WhoisProfile.initContextWithProfile(WhoisProfile.java:27)
        at net.ripe.db.whois.db.WhoisServer.main(WhoisServer.java:41)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'acl.database.url' in value "${acl.database.url}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:296)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:217)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:147)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:85)
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:225)
        ... 8 more`
        
Thanks in advance :)

**Comment by eshryane** [comment]
Hello, firstly apologies for the delay in replying, the DB team supports the Whois application on a "best effort" basis, so responses to issues may sometimes take some time depending on what we're currently working on.

Re. (1) we removed the default properties file as it causes uncertainty about the application state when running in multiple environments. We had a mix of defaults from that internal file, in addition to values set in an external properties file. We now instead set sensible defaults when values are autowired, where we can, and no internal properties file.

Re (2) the init script assumes a properties file in the current directory (`-Dwhois.config=properties`), can you copy the contents of the (deleted) properties file from the repo as the basis for your own standalone file in that location?
